language: cpp
compiler: gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libmysqlclient-dev libperl-dev libboost-dev liblua5.1-0-dev zlib1g-dev
script:
  - cmake -G "Unix Makefiles" -DEQEMU_BUILD_TESTS=ON -DEQEMU_ENABLE_BOTS=ON
  - make
  - ./bin/tests
branches:
  only:
    - master
    - stable
notifications:
  email: false
  irc:
    channels: "irc.eqemulator.net#eqemucoders"
os: linux